In [34]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
years = list(range(2004, 2025))
url_start = 'https://basketball.realgm.com/international/league/12/French-Jeep-Elite/stats/{year}/Per_48/Qualified/All/points/{position}/desc/1/Regular_Season'
data = []  # List to store parsed data
for year in years:
    for position in ['PG', 'SG', 'SF', 'PF', 'C']:
        url = url_start.format(year=year, position=position)  # Correctly format the URL
        response = requests.get(url)
        soup = BeautifulSoup(response.content, 'html.parser')
        for row in soup.select('.tablesaw tbody tr'):
            player = [year, position]  # Add the year and position to the player data
            player += [cell.text.strip() for cell in row.find_all('td')]
            data.append(player)
# Creating DataFrame from the collected data
columns = ['Year', 'Position', '#', 'Player', 'Team', 'GP', 'MPG', 'PPG', 'FGM', 'FGA', 'FG%', '3PM', '3PA', '3P%',
           'FTM', 'FTA', 'FT%', 'ORB', 'DRB', 'RPG', 'APG', 'SPG', 'BPG', 'TOV', 'PF']
df = pd.DataFrame(data, columns=columns)
# Save DataFrame to a CSV file
df.to_csv('euroleague_stats_with_positions.csv', index=False)
# Display DataFrame
df

,Year,Position,#,Player,Team,GP,MPG,PPG,FGM,FGA,...,FTA,FT%,ORB,DRB,RPG,APG,SPG,BPG,TOV,PF
0,2005,PG,1,Jason Rowe,HYT,30,35.9,26.5,9.1,19.5,...,5.7,.852,1.0,3.7,4.6,8.4,3.1,0.0,4.7,2.9
1,2005,PG,2,Terrell Lyday,LYV,36,32.9,25.8,9.0,18.0,...,6.0,.791,1.0,4.5,5.5,6.4,2.5,0.5,3.4,3.9
2,2005,PG,3,Marcus Wilson,GRV,23,31.0,25.0,8.0,17.5,...,6.5,.897,0.5,1.8,2.2,4.2,1.0,0.1,2.5,3.2
3,2005,PG,4,Afik Nissim,STR,37,19.7,24.4,8.3,17.9,...,4.2,.825,0.6,3.2,3.8,5.4,1.6,0.0,2.9,3.5
4,2005,PG,5,Mire Chatman,PAU,27,32.8,23.3,8.5,17.9,...,6.0,.700,1.0,4.2,5.2,8.8,3.5,0.2,3.4,2.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2698,2024,C,27,Mattias Markusson,CHA,19,14.3,15.0,6.2,9.4,...,3.2,.833,4.4,8.5,12.9,1.9,1.1,1.1,2.6,5.3
2699,2024,C,28,Wilfried Yeguete,LEM,29,21.4,14.6,6.3,13.0,...,3.9,.490,5.5,9.4,14.8,3.4,1.7,0.3,3.6,6.3
2700,2024,C,29,Hamady Ndiaye,N92,27,14.7,12.0,5.4,7.3,...,2.5,.429,3.1,3.1,6.3,1.8,0.7,2.8,1.6,5.4
2701,2024,C,30,John Egbunu,LYV,15,11.9,11.8,4.3,7.2,...,6.2,.522,3.8,7.2,11.0,0.5,0.3,1.3,4.3,7.2
2702,2024,C,31,Leon Kratzer,PAR,28,17.4,8.7,4.0,7.8,...,1.4,.429,6.4,7.9,14.3,2.3,1.9,1.6,3.0,7.8

In [9]:
df['Position'] = df['Position'].replace(['PG', 'SG'], 'G')
df['Position'] = df['Position'].replace(['SF', 'PF'], 'F')

In [8]:
df.loc[:, 'GP':] = df.loc[:,'GP':].astype(float)
df.loc[:, 'MPG':] = df.loc[:,'MPG':].mul(1.25)

/var/folders/7h/233xrn2x20n5883dfdqwt5zr0000gn/T/ipykernel_23284/2958420313.py:1: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.loc[:, 'GP':] = df.loc[:,'GP':].astype(float)

In [31]:
df_center = df[df['Position'] == 'C']
df_center_filtered = df_center[(df_center['RPG'] >= 13.0) & (df_center['3PA'] >= 2.0 ) & (df_center['APG'] >= 3.0)& (df_center['Year'] <= 2023)]

In [32]:
df_center

,Year,Position,#,Player,Team,GP,MPG,PPG,FGM,FGA,...,FTA,FT%,ORB,DRB,RPG,APG,SPG,BPG,TOV,PF
102,2005,C,1,Claude Marquis,CHO,30.0,33.000,35.125,13.625,23.750,...,11.750,0.83375,5.250,7.375,12.625,1.875,1.500,0.750,6.000,6.500
103,2005,C,2,T.J. Lux,PAU,30.0,25.625,33.875,12.625,20.500,...,10.375,1.06125,5.875,8.000,13.875,3.250,2.500,1.375,3.125,9.750
104,2005,C,3,Dan McClintock,NAN,37.0,32.625,32.375,13.000,22.000,...,9.125,0.87625,3.625,8.375,12.000,1.750,1.000,2.750,4.500,6.750
105,2005,C,4,Sharif Fajardo,STR,36.0,32.375,30.750,10.875,23.000,...,9.500,0.98000,3.750,7.250,10.875,2.000,2.125,0.375,4.250,6.750
106,2005,C,5,Boniface Ndong,DIJ,30.0,36.000,30.250,12.375,24.500,...,7.750,0.87000,5.875,11.125,17.000,2.875,1.375,2.250,5.250,6.625
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2698,2024,C,27,Mattias Markusson,CHA,19.0,17.875,18.750,7.750,11.750,...,4.000,1.04125,5.500,10.625,16.125,2.375,1.375,1.375,3.250,6.625
2699,2024,C,28,Wilfried Yeguete,LEM,29.0,26.750,18.250,7.875,16.250,...,4.875,0.61250,6.875,11.750,18.500,4.250,2.125,0.375,4.500,7.875
2700,2024,C,29,Hamady Ndiaye,N92,27.0,18.375,15.000,6.750,9.125,...,3.125,0.53625,3.875,3.875,7.875,2.250,0.875,3.500,2.000,6.750
2701,2024,C,30,John Egbunu,LYV,15.0,14.875,14.750,5.375,9.000,...,7.750,0.65250,4.750,9.000,13.750,0.625,0.375,1.625,5.375,9.000
2702,2024,C,31,Leon Kratzer,PAR,28.0,21.750,10.875,5.000,9.750,...,1.750,0.53625,8.000,9.875,17.875,2.875,2.375,2.000,3.750,9.750

In [13]:
df_center.columns

Index(['Year', 'Position', '#', 'Player', 'Team', 'GP', 'MPG', 'PPG', 'FGM',
       'FGA', 'FG%', '3PM', '3PA', '3P%', 'FTM', 'FTA', 'FT%', 'ORB', 'DRB',
       'RPG', 'APG', 'SPG', 'BPG', 'TOV', 'PF'],
      dtype='object')

In [19]:
df_forward = df[df['Position'] == 'F']
df_forward_filtered = df_forward[(df_forward['3PM'] >= 30.0) & (df_forward['3PA'] >= 35.0 ) & (df_center['FGA'] >= 3.0)]

/var/folders/7h/233xrn2x20n5883dfdqwt5zr0000gn/T/ipykernel_23284/3279395072.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_forward_filtered = df_forward[(df_forward['3PM'] >= 30.0) & (df_forward['3PA'] >= 35.0 ) & (df_center['FGA'] >= 3.0)]

In [33]:
df_forward

,Year,Position,#,Player,Team,GP,MPG,PPG,FGM,FGA,...,FTA,FT%,ORB,DRB,RPG,APG,SPG,BPG,TOV,PF
49,2005,F,1,Jermaine Guice,SLH,35.0,49.000,31.625,8.875,17.625,...,12.375,1.04750,1.625,5.000,6.625,8.625,4.125,0.125,4.250,3.625
50,2005,F,2,Darius Lane,ROA,26.0,39.125,31.125,11.000,24.500,...,5.250,0.99000,2.625,4.750,7.375,2.750,3.375,0.250,2.250,4.875
51,2005,F,3,John McCord,STR,36.0,29.625,30.875,12.375,20.375,...,8.750,0.84000,5.750,8.250,14.000,3.125,1.375,0.750,3.125,4.500
52,2005,F,4,Maxime Zianveni,NAN,38.0,30.625,30.375,12.125,22.500,...,6.750,0.86500,5.250,10.875,16.125,3.000,3.250,1.375,5.250,7.375
53,2005,F,5,K'Zell Wesson,GRV,33.0,42.875,29.125,11.500,20.125,...,8.500,0.79750,6.000,12.250,18.250,5.125,1.500,1.375,5.625,5.500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2667,2024,F,37,Junior Etou,STR,12.0,12.500,16.000,5.000,14.000,...,6.500,0.86500,4.000,7.000,11.000,1.000,2.000,1.000,5.500,8.000
2668,2024,F,38,Kim Tillie,CHO,18.0,21.375,15.875,4.750,11.750,...,4.750,1.09375,3.375,9.750,13.125,3.875,2.375,0.000,2.375,7.875
2669,2024,F,39,Kenny Goins,CSP,18.0,16.125,15.500,6.500,12.375,...,1.500,1.04125,3.125,9.625,12.625,2.375,0.750,1.500,2.125,11.125
2670,2024,F,40,Selom Mawugbe,LEM,21.0,22.875,14.875,6.125,11.250,...,4.375,0.75875,5.875,9.250,15.125,3.625,2.000,3.750,3.625,9.875
2671,2024,F,41,William Pfister,SQB,29.0,25.375,14.625,6.250,9.125,...,2.625,0.81750,5.000,8.625,13.625,2.250,0.625,0.625,2.000,6.875