In [1]:
import pandas as pd
import requests
pd.set_option('display.max_columns', None) # so we can see all columns in a wide DataFrame
import time
import numpy as np

In [51]:
raw_api_url ="https://stats.nba.com/stats/draftcombineplayeranthro?LeagueID=00&SeasonY"

In [ ]:
# raw_api_url ="https://stats.nba.com/stats/leaguedashplayerstats?College=&Conference=&Country=&DateFrom=&DateTo=&Division=&DraftPick=&DraftYear=&GameScope=&GameSegment=&Height=&ISTRound=&LastNGames=0&LeagueID=00&Location=&MeasureType=Base&Month=0&OpponentTeamID=0&Outcome=&PORound=0&PaceAdjust=N&PerMode=PerGame&Period=0&PlayerExperience=&PlayerPosition=&PlusMinus=N&Rank=N&Season=2023-24&SeasonSegment=&SeasonType=Regular%20Season&ShotClockRange=&StarterBench=&TeamID=0&VsConference=&VsDivision=&Weight="

In [76]:
r = requests.get(url=raw_api_url, headers=headers).json() #parses return as JSON and returns a Python object(dictionary) 
r

{'resource': 'draftcombineplayeranthro',
 'parameters': {'LeagueID': '00', 'SeasonYear': None},
 'resultSets': [{'name': 'Results',
   'headers': ['TEMP_PLAYER_ID',
    'PLAYER_ID',
    'FIRST_NAME',
    'LAST_NAME',
    'PLAYER_NAME',
    'POSITION',
    'HEIGHT_WO_SHOES',
    'HEIGHT_WO_SHOES_FT_IN',
    'HEIGHT_W_SHOES',
    'HEIGHT_W_SHOES_FT_IN',
    'WEIGHT',
    'WINGSPAN',
    'WINGSPAN_FT_IN',
    'STANDING_REACH',
    'STANDING_REACH_FT_IN',
    'BODY_FAT_PCT',
    'HAND_LENGTH',
    'HAND_WIDTH'],
   'rowSet': []}]}

In [53]:
df_cols_short = r['resultSets'][0]['headers']

In [77]:
years = ['2000-01', '2001-02', '2002-03', '2003-04', '2004-05',
         '2005-06', '2006-07', '2007-08', '2008-09', '2009-10', '2010-11', '2011-12', '2012-13', '2013-14',
         '2014-15', '2015-16', '2016-17', '2017-18', '2018-19', '2019-20', '2020-21', '2021-22', '2022-23']

dataframes = []

for year in years:
    url = (f"https://stats.nba.com/stats/draftcombineplayeranthro?LeagueID=00&SeasonYear={year}")
    r = requests.get(url=url, headers=headers).json()
    temp_df = pd.DataFrame(r['resultSets'][0]['rowSet'], columns=df_cols_short)
    temp_df['SeasonYear'] = year
    dataframes.append(temp_df)
    df_anthro_players = pd.concat(dataframes, ignore_index=True)

In [78]:
df_anthro_players

,TEMP_PLAYER_ID,PLAYER_ID,FIRST_NAME,LAST_NAME,PLAYER_NAME,POSITION,HEIGHT_WO_SHOES,HEIGHT_WO_SHOES_FT_IN,HEIGHT_W_SHOES,HEIGHT_W_SHOES_FT_IN,WEIGHT,WINGSPAN,WINGSPAN_FT_IN,STANDING_REACH,STANDING_REACH_FT_IN,BODY_FAT_PCT,HAND_LENGTH,HAND_WIDTH,SeasonYear
0,None,2124,Malik,Allen,Malik Allen,PF-C,80.25,6' 8.25'',None,None,271,86.50,7' 2.5'',109.0,9' 1'',None,None,None,2000-01
1,None,12019,Harold,Arceneaux,Harold Arceneaux,SG-SF,76.50,6' 4.5'',None,None,219,80.50,6' 8.5'',103.0,8' 7'',None,None,None,2000-01
2,None,12020,Lamont,Barnes,Lamont Barnes,PF-C,80.50,6' 8.5'',None,None,235.5,87.50,7' 3.5'',108.0,9' 0'',None,None,None,2000-01
3,None,12131,Mario,Bland,Mario Bland,PF,77.50,6' 5.5'',None,None,287,84.00,7' 0'',103.0,8' 7'',None,None,None,2000-01
4,None,2056,Primoz,Brezec,Primoz Brezec,C,84.75,7' 0.75'',None,None,243,86.00,7' 2'',110.0,9' 2'',None,None,None,2000-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1547,1630652,1630652,Trevion,Williams,Trevion Williams,C,79.25,6' 7.25'',80.75,6' 8.75'',264.60,86.75,7' 2.75'',108.5,9' 0.50'',10.8,9.0,10.25,2022-23
1548,1631258,1631258,Bryson,Williams,Bryson Williams,PF-C,NaN,None,NaN,None,None,NaN,None,NaN,None,NaN,NaN,NaN,2022-23
1549,1631109,1631109,Mark,Williams,Mark Williams,C,84.00,7' 0.00'',86.0,7' 2.00'',242.40,90.50,7' 6.50'',117.0,9' 9.00'',5.4,9.0,9.75,2022-23
1550,1630592,1630592,Jalen,Wilson,Jalen Wilson,SF-PF,NaN,None,NaN,None,None,NaN,None,NaN,None,NaN,NaN,NaN,2022-23
1551,1630855,1630855,Fanbo,Zeng,Fanbo Zeng,SF-PF,NaN,None,NaN,None,None,NaN,None,NaN,None,NaN,NaN,NaN,2022-23

In [79]:
#Export dataframe 

df_anthro_players.to_csv('player_anthro.csv', index=False)

In [80]:
# Assuming df_anthro_players is your DataFrame
# Count the number of null values in the 'HAND_WIDTH' and 'HAND_LENGTH' columns
null_count_hand_width = df_anthro_players['HAND_WIDTH'].isnull().sum()
null_count_hand_length = df_anthro_players['HAND_LENGTH'].isnull().sum()

print("Total number of null values in HAND_WIDTH column:", null_count_hand_width)
print("Total number of null values in HAND_LENGTH column:", null_count_hand_length)

Total number of null values in HAND_WIDTH column: 780
Total number of null values in HAND_LENGTH column: 780

In [85]:
# Assuming df_anthro_players is your DataFrame
# Calculate the average of the 'HAND_WIDTH' and 'HAND_LENGTH' columns
average_hand_width = df_anthro_players['HAND_WIDTH'].mean()
average_hand_length = df_anthro_players['HAND_LENGTH'].mean()

# Fill null values with the average values
df_anthro_players['HAND_WIDTH_FILLED'] = df_anthro_players['HAND_WIDTH'].fillna(average_hand_width)
df_anthro_players['HAND_LENGTH_FILLED'] = df_anthro_players['HAND_LENGTH'].fillna(average_hand_length)

# Print out the new DataFrame with filled values
df_anthro_players.tail()

,TEMP_PLAYER_ID,PLAYER_ID,FIRST_NAME,LAST_NAME,PLAYER_NAME,POSITION,HEIGHT_WO_SHOES,HEIGHT_WO_SHOES_FT_IN,HEIGHT_W_SHOES,HEIGHT_W_SHOES_FT_IN,WEIGHT,WINGSPAN,WINGSPAN_FT_IN,STANDING_REACH,STANDING_REACH_FT_IN,BODY_FAT_PCT,HAND_LENGTH,HAND_WIDTH,SeasonYear,HAND_WIDTH_FILLED,HAND_LENGTH_FILLED
1547,1630652,1630652,Trevion,Williams,Trevion Williams,C,79.25,6' 7.25'',80.75,6' 8.75'',264.60,86.75,7' 2.75'',108.5,9' 0.50'',10.8,9.0,10.25,2022-23,10.250000,9.000000
1548,1631258,1631258,Bryson,Williams,Bryson Williams,PF-C,NaN,None,NaN,None,None,NaN,None,NaN,None,NaN,NaN,NaN,2022-23,9.418394,8.723769
1549,1631109,1631109,Mark,Williams,Mark Williams,C,84.00,7' 0.00'',86.0,7' 2.00'',242.40,90.50,7' 6.50'',117.0,9' 9.00'',5.4,9.0,9.75,2022-23,9.750000,9.000000
1550,1630592,1630592,Jalen,Wilson,Jalen Wilson,SF-PF,NaN,None,NaN,None,None,NaN,None,NaN,None,NaN,NaN,NaN,2022-23,9.418394,8.723769
1551,1630855,1630855,Fanbo,Zeng,Fanbo Zeng,SF-PF,NaN,None,NaN,None,None,NaN,None,NaN,None,NaN,NaN,NaN,2022-23,9.418394,8.723769

In [82]:
# Assuming df_anthro_players is your DataFrame
# Count the number of null values in the 'HAND_WIDTH' and 'HAND_LENGTH' columns
null_count_hand_width = df_anthro_players['HAND_WIDTH_FILLED'].isnull().sum()
null_count_hand_length = df_anthro_players['HAND_LENGTH_FILLED'].isnull().sum()

print("Total number of null values in HAND_WIDTH_FILLED column:", null_count_hand_width)
print("Total number of null values in HAND_LENGTH_FILLED column:", null_count_hand_length)

Total number of null values in HAND_WIDTH_FILLED column: 0
Total number of null values in HAND_LENGTH_FILLED column: 0

In [83]:
#Export dataframe 

df_anthro_players.to_csv('player_anthro.csv', index=False)

In [84]:
# Assuming df_anthro_players is your DataFrame
# Filter for 'C', 'C-F', and 'F' positions
filtered_df = df_anthro_players[df_anthro_players['POSITION'].isin(['C', 'C-F'])]

# Print out the filtered DataFrame
filtered_df

,TEMP_PLAYER_ID,PLAYER_ID,FIRST_NAME,LAST_NAME,PLAYER_NAME,POSITION,HEIGHT_WO_SHOES,HEIGHT_WO_SHOES_FT_IN,HEIGHT_W_SHOES,HEIGHT_W_SHOES_FT_IN,WEIGHT,WINGSPAN,WINGSPAN_FT_IN,STANDING_REACH,STANDING_REACH_FT_IN,BODY_FAT_PCT,HAND_LENGTH,HAND_WIDTH,SeasonYear,HAND_WIDTH_FILLED,HAND_LENGTH_FILLED
4,None,2056,Primoz,Brezec,Primoz Brezec,C,84.75,7' 0.75'',None,None,243,86.00,7' 2'',110.0,9' 2'',None,None,None,2000-01,9.418394,8.723769
5,None,2081,Ernest,Brown,Ernest Brown,C,82.00,6' 10'',None,None,222.5,85.25,7' 1.25'',109.5,9' 1.5'',None,None,None,2000-01,9.418394,8.723769
42,None,12146,Ndongo,N'diaye,Ndongo N'diaye,C,83.50,6' 11.5'',None,None,208,87.50,7' 3.5'',112.5,9' 4.5'',None,None,None,2000-01,9.418394,8.723769
57,None,12025,Karim,Shabazz,Karim Shabazz,C,83.50,6' 11.5'',None,None,224,87.00,7' 3'',111.5,9' 3.5'',None,None,None,2000-01,9.418394,8.723769
65,None,12033,Adam,Allenspach,Adam Allenspach,C,83.50,6' 11.5'',None,None,259,84.50,7' 0.5'',107.0,8' 11'',12.4,None,None,2001-02,9.418394,8.723769
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1527,1631115,1631115,Orlando,Robinson,Orlando Robinson,C,81.75,6' 9.75'',83.0,6' 11.00'',244.40,88.00,7' 4.00'',111.0,9' 3.00'',9.5,8.75,10.0,2022-23,10.000000,8.750000
1539,1631166,1631166,Drew,Timme,Drew Timme,C,80.25,6' 8.25'',81.25,6' 9.25'',231.60,86.00,7' 2.00'',107.5,8' 11.50'',15.7,9.0,10.0,2022-23,10.000000,9.000000
1546,1631119,1631119,Jaylin,Williams,Jaylin Williams,C,80.75,6' 8.75'',82.0,6' 10.00'',236.60,85.00,7' 1.00'',108.5,9' 0.50'',8.0,8.5,10.5,2022-23,10.500000,8.500000
1547,1630652,1630652,Trevion,Williams,Trevion Williams,C,79.25,6' 7.25'',80.75,6' 8.75'',264.60,86.75,7' 2.75'',108.5,9' 0.50'',10.8,9.0,10.25,2022-23,10.250000,9.000000
1549,1631109,1631109,Mark,Williams,Mark Williams,C,84.00,7' 0.00'',86.0,7' 2.00'',242.40,90.50,7' 6.50'',117.0,9' 9.00'',5.4,9.0,9.75,2022-23,9.750000,9.000000